// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_dotnet.Data;

#nullable disable

namespace backend_dotnet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808163121_UpdateInvoiceEntity")]
    partial class UpdateInvoiceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend_dotnet.Models.AlternateComponent", b =>
                {
                    b.Property<int>("AltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("alt_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AltId"));

                    b.Property<int>("AltCompId")
                        .HasColumnType("int")
                        .HasColumnName("alt_comp_id");

                    b.Property<int>("CompId")
                        .HasColumnType("int")
                        .HasColumnName("comp_id");

                    b.Property<float>("DeltaPrice")
                        .HasColumnType("float")
                        .HasColumnName("delta_price");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.HasKey("AltId");

                    b.HasIndex("AltCompId");

                    b.HasIndex("CompId");

                    b.HasIndex("ModelId");

                    b.ToTable("alternate_component");
                });

            modelBuilder.Entity("backend_dotnet.Models.Component", b =>
                {
                    b.Property<int>("CompId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comp_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CompId"));

                    b.Property<string>("CompName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comp_name");

                    b.HasKey("CompId");

                    b.ToTable("component");
                });

            modelBuilder.Entity("backend_dotnet.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<double>("FinalAmount")
                        .HasColumnType("double")
                        .HasColumnName("final_amount");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("invoice_date");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<double>("Tax")
                        .HasColumnType("double")
                        .HasColumnName("tax");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double")
                        .HasColumnName("total_amount");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("backend_dotnet.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_detail_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceDetailId"));

                    b.Property<int>("AlternateComponentId")
                        .HasColumnType("int")
                        .HasColumnName("alternate_component_id");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int")
                        .HasColumnName("component_id");

                    b.Property<double>("DeltaPrice")
                        .HasColumnType("double")
                        .HasColumnName("delta_price");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.HasKey("InvoiceDetailId");

                    b.HasIndex("AlternateComponentId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_detail");
                });

            modelBuilder.Entity("backend_dotnet.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("manufacturer_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("manufacturer_name");

                    b.HasKey("ManufacturerId");

                    b.ToTable("manufacturer_master");
                });

            modelBuilder.Entity("backend_dotnet.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<string>("MdlName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mdl_name");

                    b.Property<double>("MinQtyPrice")
                        .HasColumnType("double")
                        .HasColumnName("min_qty_price");

                    b.Property<int>("SegmentManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("sm_id");

                    b.HasKey("ModelId");

                    b.HasIndex("SegmentManufacturerId");

                    b.ToTable("model_master");
                });

            modelBuilder.Entity("backend_dotnet.Models.SegMfg", b =>
                {
                    b.Property<int>("SegMfgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("seg_mfg_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SegMfgId"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("manufacturer_id");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int")
                        .HasColumnName("segment_id");

                    b.HasKey("SegMfgId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SegmentId");

                    b.ToTable("seg_mfg_master");
                });

            modelBuilder.Entity("backend_dotnet.Models.Segment", b =>
                {
                    b.Property<int>("segmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("segment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("segmentId"));

                    b.Property<string>("segmentName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("segment_name");

                    b.HasKey("segmentId");

                    b.ToTable("segment_master");
                });

            modelBuilder.Entity("backend_dotnet.Models.SegmentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("manufacturer_id");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int")
                        .HasColumnName("segment_id");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SegmentId");

                    b.ToTable("segment_manufacturer");
                });

            modelBuilder.Entity("backend_dotnet.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("company_address");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_name");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("GstNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gst_no");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mobile");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("registration_no");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("StNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("st_no");

                    b.Property<string>("TaxNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tax_no");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("VatNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vat_no");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("backend_dotnet.Models.VehicleDetail", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<int>("CompId")
                        .HasColumnType("int")
                        .HasColumnName("comp_id");

                    b.Property<string>("CompType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("comp_type");

                    b.Property<string>("IsConfigurable")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("is_configurable");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.HasKey("ConfigId");

                    b.HasIndex("CompId");

                    b.HasIndex("ModelId");

                    b.ToTable("vehicle_detail");
                });

            modelBuilder.Entity("backend_dotnet.Models.VehicleModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<float>("BasePrice")
                        .HasColumnType("float")
                        .HasColumnName("base_price");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("image");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int")
                        .HasColumnName("manufacturer_id");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("int")
                        .HasColumnName("minimum_quantity");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model_name");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int")
                        .HasColumnName("segment_id");

                    b.HasKey("ModelId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SegmentId");

                    b.ToTable("vehicle_model");
                });

            modelBuilder.Entity("backend_dotnet.Models.AlternateComponent", b =>
                {
                    b.HasOne("backend_dotnet.Models.Component", "AlternateComponentEntity")
                        .WithMany()
                        .HasForeignKey("AltCompId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.Component", "Component")
                        .WithMany()
                        .HasForeignKey("CompId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.VehicleModel", "Model")
                        .WithMany("AlternateComponents")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternateComponentEntity");

                    b.Navigation("Component");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("backend_dotnet.Models.Invoice", b =>
                {
                    b.HasOne("backend_dotnet.Models.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("backend_dotnet.Models.InvoiceDetail", b =>
                {
                    b.HasOne("backend_dotnet.Models.Component", "AlternateComponent")
                        .WithMany()
                        .HasForeignKey("AlternateComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternateComponent");

                    b.Navigation("Component");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("backend_dotnet.Models.Model", b =>
                {
                    b.HasOne("backend_dotnet.Models.SegmentManufacturer", "SegmentManufacturer")
                        .WithMany("Models")
                        .HasForeignKey("SegmentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SegmentManufacturer");
                });

            modelBuilder.Entity("backend_dotnet.Models.SegMfg", b =>
                {
                    b.HasOne("backend_dotnet.Models.Manufacturer", "Manufacturer")
                        .WithMany("SegMfgs")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.Segment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("backend_dotnet.Models.SegmentManufacturer", b =>
                {
                    b.HasOne("backend_dotnet.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.Segment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("backend_dotnet.Models.VehicleDetail", b =>
                {
                    b.HasOne("backend_dotnet.Models.Component", "Component")
                        .WithMany()
                        .HasForeignKey("CompId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.VehicleModel", "Model")
                        .WithMany("VehicleDetails")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("backend_dotnet.Models.VehicleModel", b =>
                {
                    b.HasOne("backend_dotnet.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dotnet.Models.Segment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("backend_dotnet.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("backend_dotnet.Models.Manufacturer", b =>
                {
                    b.Navigation("SegMfgs");
                });

            modelBuilder.Entity("backend_dotnet.Models.SegmentManufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("backend_dotnet.Models.VehicleModel", b =>
                {
                    b.Navigation("AlternateComponents");

                    b.Navigation("VehicleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
